name: projectx
description: "Um assistente virtual"
publish_to: 'none'

version: 0.0.21-alpha+22

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# Chat GPT
  chat_gpt_sdk: ^3.0.9

# DoEnv
  flutter_dotenv: ^5.1.0

# Dynamic Colors
  dynamic_color: ^1.7.0

# Device Apps
  device_apps: ^2.2.0

# Email
  flutter_email_sender: ^6.0.3

# Feedback
  feedback:
      git:
        url: https://github.com/hendrilmendes/feedback.git
        path: feedback
        ref: master

# Geo
  geolocator: ^12.0.0

# HTTP  
  http: ^1.2.1

# Intl
  intl: ^0.19.0

# Review  
  in_app_review: ^2.0.9

# Package Info
  package_info_plus: ^8.0.0

# Path Provider
  path_provider: ^2.1.3

# Provider
  provider: ^6.1.2

# Shared Preferences
  shared_preferences: ^2.2.3

# Speech to Text
  speech_to_text: ^6.6.2

# SpinKit
  flutter_spinkit: ^5.2.1

# Toast
  fluttertoast: ^8.2.6

# TTS
  flutter_tts: ^4.0.2

# Url Launcher
  url_launcher: ^6.3.0

# Wearther Icons
  weather_icons: ^3.0.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 26
  
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/
    # - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
